### PR TITLE
fix name

### PR DESCRIPTION
**Pull request by zirnc**
https://github.com/KevinNote/ResourceList/tree/main/vocabulary

根据导航，你文件名错了

### CODE REVIEW

**Comment by zirnc** [comment]
我劝你好自为之，给我权限

**Review by KevinZonda — APPROVED** [review]

**Comment by KevinZonda** [comment]
OK OK, new perm. ganted

**Comment by KevinZonda** [comment]
Love u, prof. zhu ♥

**Comment by zirnc** [comment]
good

**Pull request merged**
